international_list = [
    {'Char': 'A', 'Sequence': 'dit dah'},
    {'Char': 'B', 'Sequence': 'dah dit dit dit'},
    {'Char': 'C', 'Sequence': 'dah dit dah dit'},
    {'Char': 'D', 'Sequence': 'dah dit dit'},
    {'Char': 'E', 'Sequence': 'dit'},
    {'Char': 'F', 'Sequence': 'dit dit dah dit'},
    {'Char': 'G', 'Sequence': 'dah dah dit'},
    {'Char': 'H', 'Sequence': 'dit dit dit dit'},
    {'Char': 'I', 'Sequence': 'dit dit'},
    {'Char': 'J', 'Sequence': 'dit dah dah dah'},
    {'Char': 'K', 'Sequence': 'dah dit dah'},
    {'Char': 'L', 'Sequence': 'dit dah dit dit'},
    {'Char': 'M', 'Sequence': 'dah dah'},
    {'Char': 'N', 'Sequence': 'dah dit'},
    {'Char': 'O', 'Sequence': 'dah dah dah'},
    {'Char': 'P', 'Sequence': 'dit dah dah dit'},
    {'Char': 'Q', 'Sequence': 'dah dah dit dah'},
    {'Char': 'R', 'Sequence': 'dit dah dit'},
    {'Char': 'S', 'Sequence': 'dit dit dit'},
    {'Char': 'T', 'Sequence': 'dah'},
    {'Char': 'U', 'Sequence': 'dit dit dah'},
    {'Char': 'V', 'Sequence': 'dit dit dit dah'},
    {'Char': 'W', 'Sequence': 'dit dah dah'},
    {'Char': 'X', 'Sequence': 'dah dit dit dah'},
    {'Char': 'Y', 'Sequence': 'dah dit dah dah'},
    {'Char': 'Z', 'Sequence': 'dah dah dit dit'},
    {'Char': ' ', 'Sequence': '/'},
    {'Char': 1, 'Sequence': 'dit dah dah dah dah'},
    {'Char': 2, 'Sequence': 'dit dit dah dah dah'},
    {'Char': 3, 'Sequence': 'dit dit dit dah dah'},
    {'Char': 4, 'Sequence': 'dit dit dit dit dah'},
    {'Char': 5, 'Sequence': 'dit dit dit dit dit'},
    {'Char': 6, 'Sequence': 'dah dit dit dit dit'},
    {'Char': 7, 'Sequence': 'dah dah dit dit dit'},
    {'Char': 8, 'Sequence': 'dah dah dah dit dit'},
    {'Char': 9, 'Sequence': 'dah dah dah dah dit'},
    {'Char': 0, 'Sequence': 'dah dah dah dah dah'},
]



